[package]
name = "immutag-local-filesys"
version = "0.1.0"
authors = ["7db9a"]
edition = "2018"

[lib]
name = "immutag_local_filesys"
path = "src/mod.rs"

[dependencies]
fixture = { path = "../fixture" }
