version: "3"

services:
  coding:
    image: immutag:0.1.0
    volumes:
      - ./:/immutag
      - immutag-cargo-data-volume:/usr/local/cargo
    tty: true

volumes:
 immutag-cargo-data-volume:
   external: true
